### ISSUE TITLE
Poor default metric scheme

### ISSUE THREAD

**Issue by roumano** [sensu-plugins/sensu-plugins-openldap#4] opened 2017-04-06 13:24 UTC
this check ( metrics-ldap.rb ) is design to make a connexion to a host, 
why the default metric name used is where the sensu check is lunch ? 
```
~/bin/metrics-ldap.rb --host ldap_server01
will give me my hostname : 
pc41.XXX.XXXX.com.ldap_metrics.connections.total 1987 1491484790
pc41.XXX.XXXX.com.ldap_metrics.connections.current 9 1491484790
```
runing it to a another server will give the same metric name : 
```
~/bin/metrics-ldap.rb --host ldap_server02
will give me my hostname : 
pc41.XXX.XXXX.com.ldap_metrics.connections.total 1235 1451484602
pc41.XXX.XXXX.com.ldap_metrics.connections.current 9 1451484602
```
as workarround, i can use the --schema : 
```
~/bin/metrics-ldap.rb --host ldap_server01 --scheme ldap_server01.ldap_metrics
```
but it's a workarround ...

**Comment by GhostLyrics** [comment] 2017-04-13 20:30
There is no such thing as a wrong default in my opinion. **All** sensu metrics use the default of hostname when outputting this. It is **the job of the person configuring sensu** to make sure the correct `scheme` is used. This is especially important if you monitor more than one machine.

In this case I'd suggest using something like:

```
# (read: what you already have or this)
…ldap.rb --host example --scheme target.ldap_metrics

# (which one you prefer)
…ldap.rb --host example --scheme services.ldap.metrics.example
…ldap.rb --host example --scheme services.ldap.example.metrics
```
While this might look strange, you can then use the same idea for something like
```
check.rb --some parameter --scheme services.gitlab.another_metric
```

and make all things that are not host, but service-specific end up in the same section.

*I think what I mean to say is: checks and metrics are not designed to be smart about their output.*

**Comment by majormoses** [comment] 2017-05-06 19:55
I will largely echo with the exception that there are sometimes very poor defaults chosen. That being said this default is reasonable though possibly might be better to default to the value specified in `--host` over local hostname sd part of the default scheme. We try to have sane defaults but they are often meant to be configured as your use case dictates. I would be open to changing this and doing a major version release as changing defaults needs this to ensure that we don't change the behavior without the user consenting (I mean assuming people are version pinning your gems...if not then I can't save them from themselves).

**Comment by majormoses** [comment] 2017-06-10 20:00
@roumano are you open to proposing a better sane default? If not I am gonna close this out.

**Comment by roumano** [comment] 2017-06-10 20:14
Hi,
for me, schema should be automatic set via the host pattern
it's the case when calling via 
``` ~/bin/metrics-ldap.rb --host ldap_server01 ```

if i have to choose, i'm prefering
```
…ldap.rb --host example --scheme services.ldap.example.metrics
```

Tkx

**Comment by majormoses** [comment] 2017-06-10 23:46
What about fqdn? would it be `services.ldap.example.domain.tld.metrics`? same is true for ip addresses.

**Comment by roumano** [comment] 2017-06-12 21:59
with fqdn, it's will be sure to have unique metrics per server.
But the probability is very low and on this case, the workaround it's to set the "--scheme"
personally, i'm preferring the short name but both will make the job ;)

**Comment by majormoses** [comment] 2017-06-12 22:02
> with fqdn, it's will be sure to have unique metrics per server.

This is only true if you do not have something like a cname or load balanced setup.

> the workaround it's to set the "--scheme"

This is not a workaround and is intended behavior and brings us full circle. We do not in this case have a good enough default that makes everyone happy. At this point I do not think there is anything that we should do other than possibly put something in the readme.

**Comment by majormoses** [comment] 2017-10-07 17:46
As I don't know what we can honestly improve and lack of feedback I am closing this out. If you would like to keep discussing I am more than happy to re-open it.

**Closed as completed by majormoses** 2017-10-07 17:46 UTC
